<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.qoop</groupId>
        <artifactId>shop</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>shop-application</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-bean-filter-api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-transaction-api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-validation-api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-mapper-api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-application</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>shop-domain</artifactId>
        </dependency>
    </dependencies>
</project>
